runtime: python39

instance_class: F1

includes:
  - credentials/deploy_env_vars.yaml

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

automatic_scaling:
  max_instances: 1
  min_instances: 0
